# description
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbp: <http://dbpedia.org/property/>

SELECT DISTINCT ?description
WHERE {
    dbr:Donald_Trump dbo:abstract ?description .
  FILTER (lang(?description) = "en")
}
