PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbp: <http://dbpedia.org/property/>

SELECT  ?abstract
WHERE {
  dbr:The_Little_Prince dbo:abstract ?abstract .
 FILTER (lang(?abstract ) = "en")
}
